# Site settings
title: Saneshark Software
header-img: img/home-bg.jpg
email: kam@saneshark.com
copyright_name: Kam Karshenas
description: We're a friendly talented team of engineers crafting beautiful web applications.
baseurl: ""
url: "http://saneshark.com"
twitter_username: saneshark
github_username: sanesharksoftware
facebook_username: saneshark
email_username:  kam@saneshark.com

collections:
- portfolio_items
- services

# Build settings
markdown: kramdown
kramdown:
   input: GFM
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
