# Site settings
title: sanesharK
header-img: img/home-bg.jpg
email: kam@saneshark.com
copyright_name: Kam Karshenas
description: "I'm a Senior Software Engineer with over ten years of experience in web development and architecture. I specialize in Ruby on Rails, Elastic Search, and Small Business Consulting."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: saneshark
github_username: saneshark
facebook_username: karshenas
email_username:  kam@saneshark.com

collections:
- portfolio_items

# Build settings
markdown: kramdown
kramdown:
   input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
